from __future__ import annotations

import argparse
import csv
import math
import os
from typing import Any, Dict, List, Optional

LB = r"\\"


def read_csv(path: str) -> List[Dict[str, str]]:
    if not os.path.isfile(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def fnum(x: Any) -> Optional[float]:
    try:
        v = float(x)
        if math.isfinite(v):
            return v
    except Exception:
        pass
    return None


def fmt(x: Any, nd: int = 4) -> str:
    v = fnum(x)
    if v is None:
        return "--"
    return f"{v:.{nd}f}"


def meanstd(row: Dict[str, str], metric: str, nd: int = 4) -> str:
    return f"{fmt(row.get(metric + '_mean'), nd)}$\\pm${fmt(row.get(metric + '_std'), nd)}"


def ensure(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def write(path: str, text: str) -> None:
    ensure(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def table_backbone(summary_rows: List[Dict[str, str]]) -> str:
    rows = [r for r in summary_rows if r.get("suite") == "backbone" and r.get("dataset") == "ETTm1"]
    rows.sort(key=lambda r: (r.get("backbone", ""), r.get("variant", ""), r.get("method_label", "")))
    lines = [
        "% Auto-generated by revision_make_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Additional backbone check on ETTm1. Results are reported over paired seeds.}",
        "\\label{tab:backbone_check}",
        "\\begin{tabular}{llllll}",
        "\\toprule",
        f"Backbone & Setting & Method & RMSE$_{{avg}}$ & RMSE$_{{worst}}$ & Runtime (s) {LB}",
        "\\midrule",
    ]
    for r in rows:
        lines.append(f"{r.get('backbone','').upper()} & {r.get('variant','')} & {r.get('method_label','')} & {meanstd(r,'rmse_avg')} & {meanstd(r,'rmse_worst')} & {meanstd(r,'runtime_sec_total',1)} {LB}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def table_failure(summary_rows: List[Dict[str, str]]) -> str:
    rows = [r for r in summary_rows if r.get("suite") == "failure" and r.get("dataset") == "ETTm1"]
    rows.sort(key=lambda r: (r.get("variant", ""), r.get("failure_mode", ""), fnum(r.get("failure_rate")) or 0.0, r.get("method_label", "")))
    lines = [
        "% Auto-generated by revision_make_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Selected-client non-return evaluation. The wasted-step ratio is the fraction of assigned local steps committed to selected clients that did not return.}",
        "\\label{tab:failure_return}",
        "\\begin{tabular}{lllllll}",
        "\\toprule",
        f"Setting & Failure & Rate & Method & RMSE$_{{worst}}$ & Valid return & Wasted steps {LB}",
        "\\midrule",
    ]
    for r in rows:
        rate = f"{100.0*(fnum(r.get('failure_rate')) or 0.0):.0f}\\%"
        valid = f"{100.0*(fnum(r.get('valid_return_rate_mean')) or 0.0):.1f}\\%"
        wasted = f"{100.0*(fnum(r.get('wasted_assigned_step_ratio_mean')) or 0.0):.1f}\\%"
        lines.append(f"{r.get('variant','')} & {r.get('failure_mode','')} & {rate} & {r.get('method_label','')} & {meanstd(r,'rmse_worst')} & {valid} & {wasted} {LB}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def table_paired(paired_rows: List[Dict[str, str]]) -> str:
    rows = [
        r
        for r in paired_rows
        if r.get("metric") == "rmse_worst"
        and r.get("method") in {"CoRA-Core", "CoRA-StepAlloc"}
        and r.get("suite") in {"stress", "main", "backbone", "failure"}
    ]
    rows.sort(key=lambda r: (r.get("suite", ""), r.get("backbone", ""), r.get("dataset", ""), r.get("variant", ""), r.get("failure_mode", ""), fnum(r.get("failure_rate")) or 0.0, r.get("method", "")))
    lines = [
        "% Auto-generated by revision_make_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Paired seed-level tests for RMSE$_{worst}$ against Random. Negative differences favor the method.}",
        "\\label{tab:paired_tests}",
        "\\begin{tabular}{lllllll}",
        "\\toprule",
        f"Suite & Backbone & Setting & Method & $\\Delta$ & 95\\% CI & $p_{{Holm}}$ {LB}",
        "\\midrule",
    ]
    for r in rows:
        setting = r.get("variant", "")
        if r.get("failure_mode") not in {"", "none", None}:
            setting += f"/{r.get('failure_mode')}:{100.0*(fnum(r.get('failure_rate')) or 0.0):.0f}\\%"
        ci = f"[{fmt(r.get('ci95_low'))}, {fmt(r.get('ci95_high'))}]"
        p = r.get("paired_t_p_holm") or r.get("wilcoxon_p_holm") or r.get("paired_t_p") or ""
        lines.append(f"{r.get('suite','')} & {r.get('backbone','gru')} & {setting} & {r.get('method','')} & {fmt(r.get('mean_diff'))} & {ci} & {fmt(p,3)} {LB}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def table_main(summary_rows: List[Dict[str, str]]) -> str:
    rows = [r for r in summary_rows if r.get("suite") == "main" and r.get("backbone", "gru") == "gru"]
    rows.sort(key=lambda r: (r.get("dataset", ""), r.get("variant", ""), r.get("method_label", "")))
    lines = [
        "% Auto-generated by revision_make_latex_tables.py",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Cross-dataset GRU benchmark under the revised paired-seed protocol.}",
        "\\label{tab:main_benchmark_revised}",
        "\\begin{tabular}{lllll}",
        "\\toprule",
        f"Dataset & Setting & Method & RMSE$_{{avg}}$ & RMSE$_{{worst}}$ {LB}",
        "\\midrule",
    ]
    for r in rows:
        lines.append(f"{r.get('dataset','')} & {r.get('variant','')} & {r.get('method_label','')} & {meanstd(r,'rmse_avg')} & {meanstd(r,'rmse_worst')} {LB}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def table_ablation(summary_rows: List[Dict[str, str]]) -> str:
    rows = [r for r in summary_rows if r.get("suite") == "ablation" and r.get("dataset") == "ETTm1"]
    order = {"Random": 0, "Top-m": 1, "CoRA-Core": 2, "NoEMA": 3, "NoWarmup": 4, "NoRefresh": 5, "CoRA-StepAlloc": 6}
    rows.sort(key=lambda r: (r.get("variant", ""), order.get(r.get("method_label", ""), 99), r.get("method_label", "")))
    lines = [
        "% Auto-generated by revision_make_latex_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Mechanism ablation on ETTm1. Lower RMSE is better.}",
        "\\label{tab:mechanism_ablation}",
        "\\begin{tabular}{lllll}",
        "\\toprule",
        f"Setting & Method & RMSE$_{{avg}}$ & RMSE$_{{worst}}$ & Uplink (MB) {LB}",
        "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{r.get('variant','')} & {r.get('method_label','')} & {meanstd(r,'rmse_avg')} & "
            f"{meanstd(r,'rmse_worst')} & {meanstd(r,'uplink_mb',1)} {LB}"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser("Create LaTeX table snippets from FGCS revision summaries")
    ap.add_argument("--summary_dir", type=str, default="results/fgcs_revision/summary")
    ap.add_argument("--out_dir", type=str, default="results/fgcs_revision/tables")
    args = ap.parse_args()
    summary = read_csv(os.path.join(args.summary_dir, "revision_summary_mean_std.csv"))
    paired = read_csv(os.path.join(args.summary_dir, "revision_paired_tests.csv"))
    ensure(args.out_dir)
    write(os.path.join(args.out_dir, "table_main_benchmark_revised.tex"), table_main(summary))
    write(os.path.join(args.out_dir, "table_backbone_check.tex"), table_backbone(summary))
    write(os.path.join(args.out_dir, "table_failure_return.tex"), table_failure(summary))
    write(os.path.join(args.out_dir, "table_paired_tests.tex"), table_paired(paired))
    write(os.path.join(args.out_dir, "table_mechanism_ablation.tex"), table_ablation(summary))
    print(f"[OK] wrote LaTeX snippets under {args.out_dir}")


if __name__ == "__main__":
    main()
